name: challenge_v0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - awscli
      - torch
      - torchaudio
      - wandb
      - numpy<2
      - lightning>=2.2.1
      - einops
      - transformers<4.46
      - mirdata
      - librosa  
      - -e amt
