_wandb:
    value:
        cli_version: 0.18.3
        code_path: code/src/utils/preprocess/preprocess_guitarset.py
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": darwin-arm64
