_wandb:
    value:
        cli_version: 0.18.3
        code_path: code/src/utils/preprocess/preprocess_guitarset.py
        m:
            - "1": train/acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": validation/acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "3":
                - 2
                - 7
                - 14
                - 23
                - 55
                - 66
            "4": 3.10.0
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": darwin-arm64
